doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Symfony5\Persistence\ORM\Doctrine\Migrations': '%kernel.project_dir%/src/Infrastructure/Symfony5/Persistence/ORM/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
